trigger: none

variables:
- group: cfs-adb-upgrade-hub
- group: cfs-adb-upgrade-prod
- name: vmimageName

  value: "windows-latest"
- name: notebooksPath
  value: "notebooks"
- name: location
  value: "australiaeast"
- name: templateFile
  value: "/main.bicep"
- name: templateParameterFile
  value: "parameters/vnetUpgrade-prod.parameters.json"

pool:
  vmImage: $(vmImageName)

stages:
- template: 'deploy-pipeline.yml'
  parameters:
    stageId: "Deploy_to_Dev_Environment"
    env: "dev"
    environmentName: $(hub-environment-name)
    resourceGroupName: $(hub-resource-group-name)
    serviceConnection: $(hub-service-connection-name)
    notebooksPath: $(notebooksPath)

- template: 'deploy-pipeline.yml'
  parameters:
    dependsOn: ["Deploy_to_Dev_Environment"]
    stageId: "Deploy_to_Prod_Environment"
    env: "prod"
    environmentName: $(prod-environment-name)
    resourceGroupName: $(prod-resource-group-name)
    serviceConnection: $(prod-service-connection-name)
    notebooksPath: $(notebooksPath)
