parameters:
- name: stageId
  type: string
- name: dependsOn
  type: object
  default: []
- name: env
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: serviceConnection
  type: string
- name: notebooksPath
  type: string

- name: location
  type: string
- name: templateFile
  type: string
- name: templateParameterFile
  type: string


stages:

- stage: Preview
  dependsOn: Validate
  jobs:
  - job: Preview
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group what-if \
            --template-file '$(Build.SourcesDirectory)/${{parameters.templateFile}}' \
            --parameters '$(Build.SourcesDirectory)/${{parameters.templateParameterFile}}' \
            --resource-group '${{parameters.resourceGroupName}}'

- stage: Deploy
  jobs:
  - deployment: Deploy
    environment: BicepEnvironment
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            name: DeployBicepTemplate
            inputs:
              deploymentScope: 'Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              azureResourceManagerConnection: '$(serviceConnection)'
              action: 'Create Or Update Resource Group'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/${{parameters.templateFile}}'
              csmParametersFile: '$(Build.SourcesDirectory)/${{parameters.templateParameterFile}}'
              deploymentMode: 'Incremental'
              deploymentName: 'DeployPipelineTemplate'
