parameters:
- name: stageId
  type: string
- name: dependsOn
  type: object
  default: []
- name: env
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: serviceConnection
  type: string
- name: notebooksPath
  type: string


variables:
  location: 'australiaeast'
  templateFile: '/main.bicep'
  templateParameterFile: 'parameters/vnetUpgrade-prod.parameters.json'


stages:

- stage: Preview
  dependsOn: Validate
  jobs:
  - job: Preview
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group what-if \
            --template-file $(Build.SourcesDirectory)/$(templateFile) \
            --parameters '$(Build.SourcesDirectory)/$(templateParameterFile)' \
            --resource-group '$(resourceGroupName)'

- stage: Deploy
  jobs:
  - deployment: Deploy
    environment: BicepEnvironment
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            name: DeployBicepTemplate
            inputs:
              deploymentScope: 'Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              azureResourceManagerConnection: '$(serviceConnection)'
              action: 'Create Or Update Resource Group'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/$(templateFile)'
              csmParametersFile: '$(Build.SourcesDirectory)/$(templateParameterFile)'
              deploymentMode: 'Incremental'
              deploymentName: 'DeployPipelineTemplate'
