
trigger: none

parameters:
- name: deployEnvironment
  displayName: Target Deployment Environment
  type: string
  default: "Non-Production"
  values:
  - "Non-Production"
  - "Production"

- name: virtualEnvironment
  displayName: Virtual Environment Name (e.g "fwd-tst3")
  type: string
  default: ""

- name: useWhatIfDeploymentType

  displayName: What-If Deployment
  type: boolean
  default: true
  values:
  - false
  - true


variables:
- group: cfs-adb-upgrade-hub
- group: cfs-adb-upgrade-prod
- name: vmimageName

  value: "windows-latest"
- name: notebooksPath
  value: "notebooks"

pool:
  vmImage: $(vmImageName)

stages:
- template: templates/deploy-notebooks.yml
  parameters:
    stageId: "Deploy_to_Dev_Environment"
    env: "dev"
    environmentName: $(hub-environment-name)
    resourceGroupName: $(hub-resource-group-name)
    serviceConnection: $(hub-service-connection-name)
    notebooksPath: $(notebooksPath)

- template: templates/deploy-notebooks.yml
  parameters:
    dependsOn: ["Deploy_to_Dev_Environment"]
    stageId: "Deploy_to_Prod_Environment"
    env: "prod"
    environmentName: $(prod-environment-name)
    resourceGroupName: $(prod-resource-group-name)
    serviceConnection: $(prod-service-connection-name)
    notebooksPath: $(notebooksPath)
